/* Auto-generated data file moved out of hausa_explorer.html */

const HAUSA_VOCABULARY = {
    "Sannu": {"translation": "Hello (general greeting)", "example": "Sannu, yaya aiki? (Hello, how is work?)"},
    "Na gode": {"translation": "Thank you", "example": "Na gode kwarai. (Thank you very much.)"},
    "Eh": {"translation": "Yes", "example": "Eh, zan zo. (Yes, I will come.)"},
    "A'a": {"translation": "No", "example": "A'a, ban gani ba. (No, I did not see it.)"},
    "Don Allah": {"translation": "Please", "example": "Don Allah ka taimake ni. (Please help me.)"},
    "Yi hak'uri": {"translation": "Sorry / Pardon me", "example": "Yi hak'uri, na makara. (Sorry, I am late.)"},
    "Ina kwana?": {"translation": "Good morning", "example": "Ina kwana? Lafiya lau. (Good morning? Very fine.)"},
    "Yaya aiki?": {"translation": "How is work?", "example": "Yaya aiki? Aiki da godiya. (How is work? Work with thanks.)"},
    "Sai anjima": {"translation": "See you later", "example": "Mun gama, sai anjima. (We are done, see you later.)"},
    "Sai gobe": {"translation": "See you tomorrow", "example": "Na tafi, sai gobe. (I am going, see you later.)"},
    "Lafiya lau": {"translation": "Very fine / I am well", "example": "Yaya kake? Lafiya lau. (How are you? I am very fine.)"},
    "Barka da zuwa": {"translation": "Welcome", "example": "Barka da zuwa gidan mu. (Welcome to our house.)"},
    "Muna goode": {"translation": "We thank you (plural)", "example": "Muna goode da abinci. (We thank you for the food.)"},
    "A'a ba kome": {"translation": "You're welcome / No problem", "example": "Na gode. A'a ba kome. (Thank you. You're welcome.)"},
    "Na ji dadi": {"translation": "I enjoyed it / I am happy", "example": "Na ji dadi sosai. (I enjoyed it very much.)"},
    "Ina lafiya?": {"translation": "Are you well?", "example": "Ina lafiya? Lafiya lau. (Are you well? Very well.)"},
    "Bari in tafi": {"translation": "Let me go", "example": "Yamma ta yi, bari in tafi. (It is evening, let me go.)"},
    "Ka dawo lafiya": {"translation": "Return safely (said to someone leaving)", "example": "Ka dawo lafiya. Sai anjima. (Return safely. See you later.)"},
    "Barka da yamma": {"translation": "Good evening", "example": "Barka da yamma, yaya gida? (Good evening, how is home?)"},
    "Na gaji": {"translation": "I am tired", "example": "Bayan aiki, na gaji sosai. (After work, I am very tired.)"},
    "Miji": {"translation": "Husband", "example": "Miji na yana da kirki. (My husband is kind.)"},
    "Mata": {"translation": "Wife / Woman", "example": "Matata ta dafa abinci. (My wife cooked the food.)"},
    "Yaro": {"translation": "Boy / Child", "example": "Yaron yana wasa. (The boy is playing.)"},
    "Yarinya": {"translation": "Girl", "example": "Yarinyar tana karatu. (The girl is reading.)"},
    "Aboki": {"translation": "Friend (male)", "example": "Wannan abokina ne. (This is my friend.)"},
    "Kawa": {"translation": "Friend (female)", "example": "Kawata ta zo ziyara. (My friend came to visit.)"},
    "Uba": {"translation": "Father", "example": "Ubana ya tafi kasuwa. (My father went to the market.)"},
    "Uwa": {"translation": "Mother", "example": "Uwata tana gida. (My mother is at home.)"},
    "Wa": {"translation": "Older brother", "example": "Wana ya saya min riga. (My older brother bought me a shirt.)"},
    "Kanwa": {"translation": "Younger sister", "example": "Kanwata tana son zaki. (My younger sister likes sweets.)"},
    "Dan uwa": {"translation": "Relative / Brother (general)", "example": "Shi dan uwa na ne. (He is my relative.)"},
    "Yaya": {"translation": "Sibling / How (plural)", "example": "Yaya nawa sun zo. (My siblings came.)"},
    "Kaka": {"translation": "Grandfather / Grandmother", "example": "Kakana ya bani labari. (My grandfather told me a story.)"},
    "Jikoki": {"translation": "Grandchildren", "example": "Jikoki suna wasa a waje. (The grandchildren are playing outside.)"},
    "Mutum": {"translation": "Person / Man", "example": "Mutum mai kirki. (A kind person.)"},
    "Mace": {"translation": "Woman", "example": "Mace tana aiki tukuru. (The woman is working hard.)"},
    "Maza": {"translation": "Men", "example": "Maza suna tattaunawa. (The men are discussing.)"},
    "Yara": {"translation": "Children (plural)", "example": "Yara suna makaranta. (The children are at school.)"},
    "Malam": {"translation": "Teacher / Learned man", "example": "Malam ya koyar da mu. (The teacher taught us.)"},
    "Dalibi": {"translation": "Student (male)", "example": "Dalibi yana karatu. (The student is reading.)"},
    "Likita": {"translation": "Doctor", "example": "Likita ya duba ni. (The doctor examined me.)"},
    "Sarki": {"translation": "Emir / King", "example": "Sarki yana zaune a fada. (The Emir is sitting in the palace.)"},
    "Bawa": {"translation": "Servant / Slave (historical)", "example": "Bawa ya yi aiki mai tsawo. (The servant did long work.)"},
    "Mai gida": {"translation": "House owner / Master", "example": "Mai gida ya dawo. (The master has returned.)"},
    "Ma'aikaci": {"translation": "Worker / Employee", "example": "Ma'aikaci ya tafi hutu. (The employee went on holiday.)"},
    "Dan kasuwa": {"translation": "Trader / Businessman", "example": "Dan kasuwa ya sayar da kaya. (The businessman sold the goods.)"},
    "Masu": {"translation": "Owners / Those who have", "example": "Masu kudi. (The rich people.)"},
    "Ba\u0142o": {"translation": "Guest / Stranger", "example": "Ba\u0142o ya zo ziyara. (A guest came to visit.)"},
    "Ma\u0101wabci": {"translation": "Neighbor", "example": "Ma\u0101wabcin mu yana da kirki. (Our neighbor is kind.)"},
    "Jama'a": {"translation": "People / Community", "example": "Jama'a sun hallara. (The people gathered.)"},
    "Gida": {"translation": "House / Home", "example": "Na dawo gida. (I have returned home.)"},
    "Kasuwa": {"translation": "Market", "example": "Kasuwar tana cike da mutane. (The market is full of people.)"},
    "Kudi": {"translation": "Money", "example": "Ba ni da kudi a yanzu. (I don't have money right now.)"},
    "Littafi": {"translation": "Book", "example": "Ina karanta littafi. (I am reading a book.)"},
    "Mota": {"translation": "Car", "example": "Motar tana da sauri. (The car is fast.)"},
    "Hanya": {"translation": "Road / Path", "example": "Hanya tana da tsawo. (The road is long.)"},
    "Wuri": {"translation": "Place / Location", "example": "Wannan wuri yana da kyau. (This place is beautiful.)"},
    "Fata": {"translation": "Skin / Hope", "example": "Ina da fata mai kyau. (I have good hope.)"},
    "Kofa": {"translation": "Door / Gate", "example": "Bude kofa don shiga. (Open the door to enter.)"},
    "Gado": {"translation": "Bed", "example": "Yaro yana barci a gado. (The boy is sleeping in bed.)"},
    "Ruwa": {"translation": "Water", "example": "Ina jin kishirwa, ina son ruwa. (I am thirsty, I want water.)"},
    "Wuta": {"translation": "Fire", "example": "Wuta tana da zafi. (Fire is hot.)"},
    "Iska": {"translation": "Air / Wind", "example": "Iska tana kadawa. (The wind is blowing.)"},
    "Kasa": {"translation": "Down / Ground / Land", "example": "Yaro yana zaune a kasa. (The boy is sitting on the ground.)"},
    "Sama": {"translation": "Up / Sky", "example": "Jirgin sama yana sama. (The airplane is up.)"},
    "Tufafi": {"translation": "Clothes", "example": "Ina sawa tufafi sabo. (I am wearing new clothes.)"},
    "Takalmi": {"translation": "Shoe", "example": "Na saya takalmi baki. (I bought a black shoe.)"},
    "Kofi": {"translation": "Cup / Mug", "example": "Ka ba ni kofi ruwa. (Give me a cup of water.)"},
    "Allo": {"translation": "Board / Tablet", "example": "Malam ya rubuta a allo. (The teacher wrote on the board.)"},
    "Kujera": {"translation": "Chair", "example": "Kujerar tana da dadi. (The chair is comfortable.)"},
    "Tebur": {"translation": "Table", "example": "Akwai abinci a kan tebur. (There is food on the table.)"},
    "Waya": {"translation": "Phone / Wire", "example": "Wayata tana bugawa. (My phone is ringing.)"},
    "Hoto": {"translation": "Picture / Photo", "example": "Na dauki hoto. (I took a picture.)"},
    "Jirgi": {"translation": "Vehicle / Plane", "example": "Jirgin mota yana da sauri. (The bus is fast.)"},
    "Keke": {"translation": "Bicycle", "example": "Yaron yana hawan keke. (The boy is riding a bicycle.)"},
    "Ganye": {"translation": "Leaf / Herb", "example": "Miyan kuka ana yi da ganye. (Baobab soup is made with leaves.)"},
    "Itace": {"translation": "Tree / Wood", "example": "Muna da itace mai tsayi. (We have a tall tree.)"},
    "Duwatsu": {"translation": "Stones / Rocks", "example": "Akwai duwatsu a hanya. (There are stones on the road.)"},
    "Kogi": {"translation": "River", "example": "Kogi yana da zurfi. (The river is deep.)"},
};